"""your message

Revision ID: d9f9607b6d81
Revises: b48825671f8b
Create Date: 2024-10-21 21:08:42.614572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f9607b6d81'
down_revision = 'b48825671f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
